import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'D-Starite Technologies',
  description: 'Generated by D-Starite Technologies with Love',
  faNavicon:'https://i.imgur.com/4CA3YuG.jpeg',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Mount the toast provider */}
        <Toaster position="top-right" reverseOrder={false} />
        
        {children}
      </body>
    </html>
  );
}
